TheoBerlin/GameProject

.gitignore, log.txt
Output logs should not be stored in git
=> Ignore and delete log.txt

GameProject/Engine/Config.h, GameProject/Engine/Imgui/imconfig.h, GameProject/Engine/Imgui/imgui.cpp, GameProject/Engine/Imgui/imgui.h, GameProject/Engine/Imgui/imgui_demo.cpp, GameProject/Engine/Imgui/imgui_draw.cpp, GameProject/Engine/Imgui/imgui_impl_glfw.cpp, GameProject/Engine/Imgui/imgui_impl_glfw.h, GameProject/Engine/Imgui/imgui_impl_opengl3.cpp, GameProject/Engine/Imgui/imgui_impl_opengl3.h, GameProject/Engine/Imgui/imgui_internal.h, GameProject/Engine/Imgui/imgui_widgets.cpp, GameProject/Engine/Imgui/imstb_rectpack.h, GameProject/Engine/Imgui/imstb_textedit.h, GameProject/Engine/Imgui/imstb_truetype.h, GameProject/Engine/Rendering/Display.cpp, GameProject/GameProject.vcxproj, GameProject/imgui.ini
This merge just adds the files for imgui into the engine folder. Also adds the necessary code to init and create the context for imgu, as well as cleanup
Also fixed warnings and mismatches
=> Added imgui, clean solution

GameProject/Engine/Components/Component.cpp, GameProject/Engine/Components/Component.h, GameProject/Engine/Events/Events.h, GameProject/Game/components/ArrowGuider.cpp, GameProject/Game/components/ArrowGuider.h, GameProject/GameProject.vcxproj, GameProject/Tests/Events_test.cpp, GameProject/Tests/Tests.vcxproj, GameProject/Tests/arrow_test.cpp, GameProject/Tests/main_test.cpp
- Changed construction sequence of components
- main_test.cpp now uses the Display class instead of interacting with GLFW directly
- Added test section for event bus
- Added test case for arrow guider
=> Controllable arrow

GameProject/Engine/Components/Camera.cpp, GameProject/Engine/Components/Camera.h
Three functions added, amazing.
=> Added gets for position, view and projection.

GameProject/Engine/InputHandler.cpp
1 whole row of code to do that, amazing.
=> Optimized inputHandler

GameProject/Engine/Components/FreeMove.cpp, GameProject/Engine/Components/FreeMove.h, GameProject/Game/Components/ArrowGuider.cpp, GameProject/Game/Components/ArrowGuider.h
Limits pitch in Arrow Guider and Free Move.
=> Limit pitch in camera components

GameProject/Engine/Components/FreeMove.cpp, GameProject/Engine/Components/FreeMove.h, GameProject/Engine/Events/Events.h, GameProject/Engine/InputHandler.cpp, GameProject/Engine/InputHandler.h, GameProject/Game/Components/ArrowGuider.cpp, GameProject/Game/Components/ArrowGuider.h, GameProject/Utils/Settings.json
- InputHandler now calculates the delta distance moved from the last event call for mouse movement.
- The even MouseMoveEvent now holds the delta movement.
- MouseMoveEvent now sends out ints for pos and deltas instead of doubles, since it is all in pixels.
- Updated ArrowGuider and FreeMove to comply with the new Event change for better performance.
=> InputHandler optimization and added functionality

GameProject/Engine/GUI/Button.cpp, GameProject/Engine/GUI/Button.h, GameProject/Engine/GUI/GUI.cpp, GameProject/Engine/GUI/GUI.h, GameProject/Engine/GUI/Panel.cpp, GameProject/Engine/GUI/Panel.h, GameProject/Engine/States/StateManager.cpp, GameProject/Game/States/MenuState.cpp
- Fixed button still being active after entering the game state.
=> Fixed button still being active.

GameProject/Engine/AssetManagement/Model.cpp, GameProject/Engine/Components/FreeMove.cpp, GameProject/Engine/Components/PlayerCollision.cpp, GameProject/Engine/InputHandler.cpp, GameProject/Engine/Rendering/Display.cpp, GameProject/Engine/Rendering/GLAbstraction/Framebuffer.cpp, GameProject/Engine/Rendering/GLAbstraction/Shader.cpp, GameProject/Engine/Rendering/GLAbstraction/UniformBuffer.cpp, GameProject/Engine/Rendering/GUIRenderer.cpp, GameProject/Engine/Sound/Sound.cpp, GameProject/Engine/Sound/SoundContext.cpp, GameProject/Game/Components/OversightController.cpp, GameProject/Game/States/MenuState.cpp, GameProject/Utils/Settings.cpp
Also made some include paths shorter by removing the "../../" in front.
=> Removed unnecessary includes of logger.h

GameProject/Game/Components/Hover.cpp, GameProject/Game/Components/Hover.h, GameProject/Game/GameLogic/TargetManager.cpp, GameProject/Game/GameLogic/TargetManager.h, GameProject/GameProject.vcxproj
Includes a Hover component which animates static targets with rotation and translation. The hover animation is reset when changing phases.
=> Target hover

GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.cpp
=> Collisioncoloring

GameProject/Engine/Entity/Transform.cpp, GameProject/Engine/Entity/Transform.h, GameProject/Game/Components/Hover.cpp, GameProject/Game/Components/Hover.h
The static targets' hover animations now start at random times.
Also added Transform::getYawPitchRoll but ended up not using it. Kept it as it might be useful in the future.
=> Randomized hover starting time

GameProject/Game/GameLogic/ReplaySystem.cpp
Fixed crash when colliding with floor
=> Particle system

GameProject/Engine/Entity/Transform.cpp, GameProject/Engine/Entity/Transform.h, GameProject/Game/Level/LevelStructure.cpp
Also removed the ambiguous function `setRotation(quat)` as there was already a `setRotationQuat(quat)`.
=> Remove getRotation and fix getYawPitchRoll

GameProject/Game/GameLogic/Phases/ReplayPhase.cpp, GameProject/Game/GameLogic/Phases/ReplayPhase.h
- Removed setSize of timeBar elements to avoid unnecessary memory allocation.
=> Fixed memory issue with replay bar

GameProject/Engine/GUI/Button.cpp, GameProject/Engine/GUI/Button.h, GameProject/Engine/GUI/ScrollPanel/List.cpp, GameProject/Engine/GUI/ScrollPanel/List.h, GameProject/Engine/GUI/ScrollPanel/ScrollPanel.cpp, GameProject/Engine/GUI/ScrollPanel/ScrollPanel.h, GameProject/Engine/Rendering/Pipeline.cpp, GameProject/Game/Level/LevelParser.cpp, GameProject/Game/Level/exampleLevel.json, GameProject/Game/Level/exampleLevel2.json, GameProject/Game/States/MenuState.cpp
- Added two example maps
- Added scale to boxes
- Added active button to scroll list to show which is currently selected
=> Menu gui & maps

GameProject/Game/Components/PathTreader.cpp, GameProject/Game/Components/PathTreader.h, GameProject/Game/Level/LevelParser.cpp, GameProject/Game/States/EditorState.cpp
Made the code cleaner. This will also slightly improve performance when saving levels.
=> Level editor cleanup

GameProject/Game/Level/LevelParser.cpp
=> Removed lowercase i

GameProject/Game/GameLogic/Phases/ReplayPhase.cpp, GameProject/Game/GameLogic/Phases/ReplayPhase.h, GameProject/Game/GameLogic/ReplaySystem.cpp, GameProject/Game/GameLogic/ReplaySystem.h, GameProject/Game/Level/Levels/newLevel.json
=> Gui replay show hits

GameProject/Game/GameLogic/Phases/GuidingPhase.cpp, GameProject/Game/GameLogic/Phases/GuidingPhase.h
=> Added collision to arrow and roof

GameProject/Engine/GUI/Panel.cpp, GameProject/Game/GameLogic/Phases/ReplayPhase.cpp, GameProject/Game/Level/Levels/Level 1.json
=> Fixed panel not getting a texture at start

GameProject/Engine/GUI/Panel.cpp, GameProject/Game/Level/Levels/Level 2.json, GameProject/Game/Level/Levels/level.json, GameProject/Game/Level/Levels/newLevel.json
=> Fixed panel not resize when bigger text

.gitignore, GameProject/Game/GameLogic/GameEvents.h, GameProject/Game/GameLogic/Phases/ReplayPhase.cpp, GameProject/Game/GameLogic/Phases/ReplayPhase.h, GameProject/Game/GameLogic/ReplaySystem.h, GameProject/Game/GameLogic/ScoreManager.cpp, GameProject/Game/GameLogic/TargetManager.cpp, GameProject/Game/GameLogic/TargetManager.h, GameProject/Game/Level/Level.h, GameProject/Game/Level/LevelParser.cpp, GameProject/Game/Level/Levels/level.json, GameProject/Game/Level/ReplayParser.cpp, GameProject/Game/Level/ReplayParser.h, GameProject/Game/States/MenuState.cpp, GameProject/Game/States/MenuState.h, GameProject/GameProject.vcxproj
Replays of high score playthroughs are written to file using a static class `ReplayParser`.
The next step is to read these replay files and render the game during level select.
=> Replay parser

GameProject/Engine/Components/Camera.cpp, GameProject/Engine/Entity/EntityManager.cpp, GameProject/Engine/Rendering/Lighting/LightManager.cpp, GameProject/Engine/Rendering/Pipeline.cpp, GameProject/Engine/Rendering/Pipeline.h, GameProject/Engine/Rendering/Renderer.cpp, GameProject/Engine/Rendering/Shaders/ShaderShells/EntityShader.h, GameProject/Engine/States/State.cpp, GameProject/Engine/States/State.h, GameProject/Game/GameLogic.cpp, GameProject/Game/GameLogic.h, GameProject/Game/GameLogic/LevelPreviewer.cpp, GameProject/Game/GameLogic/LevelPreviewer.h, GameProject/Game/GameLogic/Phases/OverviewPhase.cpp, GameProject/Game/GameLogic/ReplaySystem.cpp, GameProject/Game/GameLogic/ReplaySystem.h, GameProject/Game/Level/Level.h, GameProject/Game/Level/LevelParser.cpp, GameProject/Game/Level/LevelParser.h, GameProject/Game/States/EditorState.cpp, GameProject/Game/States/EditorState.h, GameProject/Game/States/GameState.cpp, GameProject/Game/States/GameState.h, GameProject/Game/States/MenuState.cpp, GameProject/Game/States/MenuState.h, GameProject/GameProject.vcxproj
Introducing level previews. When selecting levels in the menu, the currently selected level is loaded and rendered behind the GUI.
=> Level previews

GameProject/Game/GameLogic/Phases/GuidingPhase.cpp, GameProject/Game/GameLogic/Phases/ReplayPhase.cpp
Fixed bugs with dt freezing caused by slowing time
=> Fix timestop
